//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chucvu
    {
        public int id { get; set; }
        public int id_ns { get; set; }
        public int chucvu1 { get; set; }
        public System.DateTime chucvu_ngay { get; set; }
        public Nullable<System.DateTime> chucvu_ngayhet { get; set; }
        public Nullable<bool> chucvu_noibo { get; set; }
        public string chucvu_soqd { get; set; }
        public Nullable<System.DateTime> chucvu_ngayky { get; set; }
    
        public virtual HoSoGoc HoSoGoc { get; set; }
    }
}
