//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_NoneFlight
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<int> ObjKindID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Aves_From { get; set; }
        public Nullable<System.DateTime> Aves_To { get; set; }
        public string Aves_Note { get; set; }
        public Nullable<bool> Printed { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> BreakDate { get; set; }
        public string BreakDecision { get; set; }
        public Nullable<System.DateTime> BreakSigned { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isLocked { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string ApproverID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual CR_NoneFlight_Category CR_NoneFlight_Category { get; set; }
    }
}
