//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_NoneFlight_Category
    {
        public CR_NoneFlight_Category()
        {
            this.CR_NoneFlight = new HashSet<CR_NoneFlight>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Group { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Valid_From { get; set; }
        public Nullable<System.DateTime> Valid_to { get; set; }
        public string KBCode { get; set; }
        public string TrnCode { get; set; }
        public string ActivityType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
    
        public virtual ICollection<CR_NoneFlight> CR_NoneFlight { get; set; }
    }
}
