//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ERMSEntities : DbContext
    {
        public ERMSEntities()
            : base("name=ERMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HR_GBLuyke> HR_GBLuyke { get; set; }
        public DbSet<HR_Party> HR_Party { get; set; }
        public DbSet<Sys_Account> Sys_Account { get; set; }
        public DbSet<CR_NoneFlight> CR_NoneFlight { get; set; }
        public DbSet<CR_NoneFlight_Category> CR_NoneFlight_Category { get; set; }
        public DbSet<CR_Flight_CoviComRoute> CR_Flight_CoviComRoute { get; set; }
        public DbSet<CR_FlightInfo> CR_FlightInfo { get; set; }
        public DbSet<CR_TimeZone> CR_TimeZone { get; set; }
        public DbSet<TMP_GSHH> TMP_GSHH { get; set; }
        public DbSet<HR_Dep_Cat> HR_Dep_Cat { get; set; }
        public DbSet<HR_Dep_Log> HR_Dep_Log { get; set; }
        public DbSet<HR_NhanThan> HR_NhanThan { get; set; }
        public DbSet<TRN_HisLearning> TRN_HisLearning { get; set; }
        public DbSet<PView_ktkl> PView_ktkl { get; set; }
        public DbSet<HR_Contract> HR_Contract { get; set; }
        public DbSet<HR_Contract_Termination> HR_Contract_Termination { get; set; }
        public DbSet<HR_Contract_Category> HR_Contract_Category { get; set; }
        public DbSet<HR_Mail> HR_Mail { get; set; }
        public DbSet<HR_MailOpsLog> HR_MailOpsLog { get; set; }
        public DbSet<HR_GroupMail> HR_GroupMail { get; set; }
        public DbSet<HR_MailinGroup> HR_MailinGroup { get; set; }
        public DbSet<HR_ThanNhan> HR_ThanNhan { get; set; }
    
        public virtual ObjectResult<USP_HR_UpdateMailGroup_Result> USP_HR_UpdateMailGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_HR_UpdateMailGroup_Result>("USP_HR_UpdateMailGroup");
        }
    }
}
