//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoGoc
    {
        public HoSoGoc()
        {
            this.chucdanhs = new HashSet<chucdanh>();
            this.chucvus = new HashSet<chucvu>();
            this.khenkluats = new HashSet<khenkluat>();
            this.ngoaingus = new HashSet<ngoaingu>();
            this.qlttlaodongs = new HashSet<qlttlaodong>();
            this.nhomchuyenmons = new HashSet<nhomchuyenmon>();
        }
    
        public int id { get; set; }
        public string mans { get; set; }
        public string ns_ho { get; set; }
        public string ns_ten { get; set; }
        public string ns_stt { get; set; }
        public int loains { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public int gioitinh { get; set; }
        public int noisinh_qg { get; set; }
        public int noisinh_tinhtp { get; set; }
        public int quequan_qg { get; set; }
        public int quequan_tinhtp { get; set; }
        public string quequan_dc { get; set; }
        public int ttru_qg { get; set; }
        public int ttru_tinhtp { get; set; }
        public string ttru_dc { get; set; }
        public int noio_qg { get; set; }
        public int noio_tinhtp { get; set; }
        public string noio_dc { get; set; }
        public int dantoc { get; set; }
        public int tongiao { get; set; }
        public int quoctich { get; set; }
        public int cmnd { get; set; }
        public string cmnd_so { get; set; }
        public System.DateTime cmnd_ngaycap { get; set; }
        public int cmnd_noicap_qg { get; set; }
        public int cmnd_noicap_tinhtp { get; set; }
        public int tpgiadinh { get; set; }
        public int tpbanthan { get; set; }
        public int tthonnhan { get; set; }
        public string dienthoaicd { get; set; }
        public string dienthoaidd { get; set; }
        public string hopthudt { get; set; }
        public int giadinhcs { get; set; }
        public bool thamgiaqdoi { get; set; }
        public string taikhoan { get; set; }
        public Nullable<int> nganhang { get; set; }
        public string masothue { get; set; }
        public byte songuoipthuoc { get; set; }
        public int hocvantd { get; set; }
        public int llchinhtri { get; set; }
        public int nhommau { get; set; }
        public byte chieucao { get; set; }
        public byte cannang { get; set; }
        public bool dangvien { get; set; }
        public Nullable<System.DateTime> dang_ngaykn { get; set; }
        public Nullable<System.DateTime> dang_ngaychuyen { get; set; }
        public Nullable<int> dang_chibo { get; set; }
        public Nullable<int> dang_chucvu { get; set; }
        public Nullable<System.DateTime> dang_ngayra { get; set; }
        public string dang_lydora { get; set; }
        public Nullable<System.DateTime> dang_kn2 { get; set; }
        public Nullable<System.DateTime> dang_ngaychyen2 { get; set; }
        public bool doanvien { get; set; }
        public Nullable<System.DateTime> doan_kn { get; set; }
        public Nullable<int> doan_chidoan { get; set; }
        public Nullable<int> doan_chucvu { get; set; }
        public Nullable<System.DateTime> doan_ngayra { get; set; }
        public Nullable<bool> doan_truongthanh { get; set; }
        public bool congdoan { get; set; }
        public System.DateTime congdoan_ngaykn { get; set; }
        public int congdoan_bophan { get; set; }
        public int congdoan_chucvu { get; set; }
        public string thebay { get; set; }
        public Nullable<System.DateTime> thebay_ngaycap { get; set; }
        public Nullable<System.DateTime> thebay_ngayhet { get; set; }
        public string thenganh { get; set; }
        public Nullable<System.DateTime> thennganh_ngaycap { get; set; }
        public Nullable<System.DateTime> thenganh_ngayhet { get; set; }
        public string socntvtobay { get; set; }
        public Nullable<System.DateTime> socntvtobay_ngayhet { get; set; }
        public Nullable<System.DateTime> ccdichvu_ngayhet { get; set; }
        public Nullable<System.DateTime> cchuanluyenb_ngayhet { get; set; }
        public int bophanlamviec { get; set; }
        public bool nangluc_gvmatdat { get; set; }
        public bool nangluc_gvtrnmb { get; set; }
        public int nangluc_nhomtv { get; set; }
        public byte[] hinhanh { get; set; }
        public string dotuyen { get; set; }
        public string ns_ghichu { get; set; }
        public string lop { get; set; }
        public string hd_sohd { get; set; }
        public Nullable<System.DateTime> bienche_ngay { get; set; }
        public Nullable<System.DateTime> bienche_tct { get; set; }
        public Nullable<System.DateTime> bienche_dtv { get; set; }
        public string mauvtuyen { get; set; }
        public Nullable<int> phep_songay { get; set; }
        public Nullable<System.DateTime> phep_tungay { get; set; }
        public string hd_ghichu { get; set; }
        public Nullable<System.DateTime> hd_hancuoi { get; set; }
        public Nullable<bool> chon { get; set; }
        public Nullable<System.DateTime> Createdhsg { get; set; }
        public Nullable<System.DateTime> Modifiedhsg { get; set; }
        public string TenStt { get; set; }
        public string Tenkd { get; set; }
        public Nullable<bool> nghiviec { get; set; }
        public Nullable<int> chuyennganh { get; set; }
        public Nullable<int> chuyennganh_xephang { get; set; }
        public string chuyennganh_noicap { get; set; }
        public Nullable<System.DateTime> chuyennganh_ngaycap { get; set; }
        public string tenkodau { get; set; }
    
        public virtual ICollection<chucdanh> chucdanhs { get; set; }
        public virtual ICollection<chucvu> chucvus { get; set; }
        public virtual ICollection<khenkluat> khenkluats { get; set; }
        public virtual ICollection<ngoaingu> ngoaingus { get; set; }
        public virtual ICollection<qlttlaodong> qlttlaodongs { get; set; }
        public virtual ICollection<nhomchuyenmon> nhomchuyenmons { get; set; }
    }
}
