//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Contract
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> TerminationID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
    }
}
