//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Dep_Log
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public int DepID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public string Note { get; set; }
        public string Manv { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDraft { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> Submitted { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
