//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_GBLuyke
    {
        public int ID { get; set; }
        public string month { get; set; }
        public string crewid { get; set; }
        public Nullable<double> f_321 { get; set; }
        public Nullable<double> f_32a { get; set; }
        public Nullable<double> f_32c { get; set; }
        public Nullable<double> f_32d { get; set; }
        public Nullable<double> f_32e { get; set; }
        public Nullable<double> f_330 { get; set; }
        public Nullable<double> f_350 { get; set; }
        public Nullable<double> f_787 { get; set; }
        public Nullable<double> f_32b { get; set; }
        public Nullable<double> f_32n { get; set; }
        public Nullable<double> f_atr72 { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> gbtvt2 { get; set; }
        public Nullable<double> gbtvt1 { get; set; }
        public Nullable<double> gbtvp { get; set; }
        public Nullable<double> gbtvc { get; set; }
    }
}
