//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Mail
    {
        public int ID { get; set; }
        public string manv { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public Nullable<bool> teamleader { get; set; }
        public Nullable<bool> coach { get; set; }
        public string Status { get; set; }
        public string ngaygiam { get; set; }
        public string chucvutv { get; set; }
        public string capnhat { get; set; }
        public Nullable<bool> matdat { get; set; }
        public Nullable<bool> acc_pub { get; set; }
        public Nullable<bool> reg_eff { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<System.DateTime> Locked { get; set; }
        public Nullable<System.DateTime> Unlocked { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
    }
}
