//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_NhanThan
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string SignFirstName { get; set; }
        public string SignLastName { get; set; }
        public string Course { get; set; }
        public string TemporaryAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string HomeTown { get; set; }
        public string Note { get; set; }
        public string Title { get; set; }
        public string PlaceOfBirth { get; set; }
        public string KN_Khac { get; set; }
        public Nullable<System.DateTime> Safety_Issued { get; set; }
        public Nullable<System.DateTime> Safety_Expired { get; set; }
    }
}
