//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Party
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public Nullable<System.DateTime> Ngayvao { get; set; }
        public Nullable<System.DateTime> Ngaychinhthuc { get; set; }
        public string Chibo { get; set; }
        public string Chucvu { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
