//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ThanNhan
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public string Relationship { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string Title { get; set; }
    }
}
