//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class khenkluat
    {
        public int id { get; set; }
        public int id_ns { get; set; }
        public bool kyluat { get; set; }
        public System.DateTime ktkl_ngay { get; set; }
        public int ktkl_nodung { get; set; }
        public Nullable<int> ktkl_capcosoketluan { get; set; }
        public Nullable<int> ktkl_capcosokhung { get; set; }
        public Nullable<System.DateTime> ktkl_capcosongaykl { get; set; }
        public Nullable<System.DateTime> ktkl_capcosongaychuyen { get; set; }
        public Nullable<System.DateTime> ktkl_ngayhop { get; set; }
        public string ktkl_hoidongkl { get; set; }
        public Nullable<int> ktkl_hoidongkhung { get; set; }
        public Nullable<int> ktkl_hinhthuc { get; set; }
        public Nullable<int> ktkl_loai { get; set; }
        public string ktkl_soqd { get; set; }
        public Nullable<System.DateTime> ktkl_ngayqd { get; set; }
        public string ktkl_nguoiky { get; set; }
        public Nullable<int> ktkl_tienthuong { get; set; }
        public Nullable<System.DateTime> ktkl_donghoso { get; set; }
        public string ktkl_ghichu { get; set; }
        public string ktkl_ndung { get; set; }
        public Nullable<System.DateTime> Createdktkl { get; set; }
        public Nullable<System.DateTime> Modifiedktkl { get; set; }
        public Nullable<bool> diem { get; set; }
    
        public virtual HoSoGoc HoSoGoc { get; set; }
    }
}
