//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngoaingu
    {
        public int id { get; set; }
        public int id_ns { get; set; }
        public int ngoaingu_loai { get; set; }
        public int ngoaingu_loaihinhdt { get; set; }
        public int ngoaingu_bangcap { get; set; }
        public System.DateTime ngoaingu_ngaycap { get; set; }
        public Nullable<System.DateTime> ngoaingu_ngayhet { get; set; }
        public Nullable<double> ngoaingu_diemnghe { get; set; }
        public Nullable<double> ngoaingu_diemnoi { get; set; }
        public Nullable<double> ngoaingu_diemdoc { get; set; }
        public Nullable<double> ngoaingu_diemviet { get; set; }
        public Nullable<double> ngoaingu_diemtong { get; set; }
        public System.DateTime ngoaingu_ngayupdate { get; set; }
        public string ngoaingu_ghichu { get; set; }
        public Nullable<int> ngoaingu_sovanbang { get; set; }
        public string ngoaingu_user { get; set; }
    
        public virtual HoSoGoc HoSoGoc { get; set; }
    }
}
