//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhomchuyenmon
    {
        public int id { get; set; }
        public int id_ns { get; set; }
        public int nhomchuyenmon1 { get; set; }
        public int chuyenmon { get; set; }
    
        public virtual HoSoGoc HoSoGoc { get; set; }
    }
}
