//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PView_ktkl
    {
        public string mans { get; set; }
        public int ktkl_hinhthuc { get; set; }
        public System.DateTime ktkl_ngayqd { get; set; }
        public bool kyluat { get; set; }
        public string TenDanhMuc { get; set; }
        public System.DateTime ktkl_ngay { get; set; }
        public string ktkl_ghichu { get; set; }
        public string ktkl_ndung { get; set; }
    }
}
