//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qlttlaodong
    {
        public qlttlaodong()
        {
            this.tamhoanhds = new HashSet<tamhoanhd>();
        }
    
        public int id { get; set; }
        public int hd_loai { get; set; }
        public System.DateTime hd_ngaykyhd { get; set; }
        public string hd_sovanban { get; set; }
        public Nullable<System.DateTime> dh_ngaykyqd { get; set; }
        public System.DateTime hd_ngayhieuluc { get; set; }
        public System.DateTime hd_ngayhet { get; set; }
        public Nullable<System.DateTime> hd_ngaychamdut { get; set; }
        public string hd_soqdchamdut { get; set; }
        public Nullable<int> hd_lydochamduthd { get; set; }
        public Nullable<System.DateTime> hd_ngayhlchamduthd { get; set; }
        public string laodong_so { get; set; }
        public Nullable<System.DateTime> laodong_ngaycap { get; set; }
        public int id_ns { get; set; }
        public string hd_soqdtongcty { get; set; }
        public Nullable<int> hd_kieuqd { get; set; }
        public string hd_sohd { get; set; }
    
        public virtual HoSoGoc HoSoGoc { get; set; }
        public virtual ICollection<tamhoanhd> tamhoanhds { get; set; }
    }
}
