//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RedantEntities : DbContext
    {
        public RedantEntities()
            : base("name=RedantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chucdanh> chucdanhs { get; set; }
        public DbSet<chucvu> chucvus { get; set; }
        public DbSet<danhmuc> danhmucs { get; set; }
        public DbSet<HoSoGoc> HoSoGocs { get; set; }
        public DbSet<khenkluat> khenkluats { get; set; }
        public DbSet<ngoaingu> ngoaingus { get; set; }
        public DbSet<qlttlaodong> qlttlaodongs { get; set; }
        public DbSet<tamhoanhd> tamhoanhds { get; set; }
        public DbSet<tbQuyetDinh> tbQuyetDinhs { get; set; }
        public DbSet<nhomchuyenmon> nhomchuyenmons { get; set; }
        public DbSet<PView_ktkl> PView_ktkl { get; set; }
    
        public virtual ObjectResult<USP_Counter_Child_Result> USP_Counter_Child()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Counter_Child_Result>("USP_Counter_Child");
        }
    
        public virtual ObjectResult<USP_Get_Chucdanh_Result> USP_Get_Chucdanh(string tenchucdanh)
        {
            var tenchucdanhParameter = tenchucdanh != null ?
                new ObjectParameter("tenchucdanh", tenchucdanh) :
                new ObjectParameter("tenchucdanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Chucdanh_Result>("USP_Get_Chucdanh", tenchucdanhParameter);
        }
    
        public virtual ObjectResult<USP_Get_Chucdanh_LCB_Result> USP_Get_Chucdanh_LCB(Nullable<System.DateTime> tungay, Nullable<int> loaichucdanh)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var loaichucdanhParameter = loaichucdanh.HasValue ?
                new ObjectParameter("loaichucdanh", loaichucdanh) :
                new ObjectParameter("loaichucdanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Chucdanh_LCB_Result>("USP_Get_Chucdanh_LCB", tungayParameter, loaichucdanhParameter);
        }
    
        public virtual ObjectResult<USP_Get_Chucdanh_Momment_Result> USP_Get_Chucdanh_Momment(string codetv, Nullable<System.DateTime> date)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Chucdanh_Momment_Result>("USP_Get_Chucdanh_Momment", codetvParameter, dateParameter);
        }
    
        public virtual ObjectResult<string> USP_Get_Chucvu(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("Manv", manv) :
                new ObjectParameter("Manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Get_Chucvu", manvParameter);
        }
    
        public virtual ObjectResult<USP_Get_ChucvuTV_All_Result> USP_Get_ChucvuTV_All(string codetv)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_ChucvuTV_All_Result>("USP_Get_ChucvuTV_All", codetvParameter);
        }
    
        public virtual ObjectResult<USP_Get_CV_Emergency_Result> USP_Get_CV_Emergency(string codetv)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_CV_Emergency_Result>("USP_Get_CV_Emergency", codetvParameter);
        }
    
        public virtual ObjectResult<USP_Get_DS_Tinh_Luong_Danh_Gia_Result> USP_Get_DS_Tinh_Luong_Danh_Gia(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_DS_Tinh_Luong_Danh_Gia_Result>("USP_Get_DS_Tinh_Luong_Danh_Gia", fromdateParameter, todateParameter);
        }
    
        public virtual ObjectResult<USP_Get_KhacToeic_Moinhat_Result> USP_Get_KhacToeic_Moinhat(string codetv)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_KhacToeic_Moinhat_Result>("USP_Get_KhacToeic_Moinhat", codetvParameter);
        }
    
        public virtual ObjectResult<USP_get_ktkl_Result> USP_get_ktkl(string codetv, Nullable<System.DateTime> tungay, Nullable<System.DateTime> toingay, Nullable<bool> loai)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var toingayParameter = toingay.HasValue ?
                new ObjectParameter("toingay", toingay) :
                new ObjectParameter("toingay", typeof(System.DateTime));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_get_ktkl_Result>("USP_get_ktkl", codetvParameter, tungayParameter, toingayParameter, loaiParameter);
        }
    
        public virtual ObjectResult<USP_Get_Ngoaingu_Result> USP_Get_Ngoaingu(string codetv, string loaingoaingu)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            var loaingoainguParameter = loaingoaingu != null ?
                new ObjectParameter("loaingoaingu", loaingoaingu) :
                new ObjectParameter("loaingoaingu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Ngoaingu_Result>("USP_Get_Ngoaingu", codetvParameter, loaingoainguParameter);
        }
    
        public virtual ObjectResult<USP_Get_Ngoaingu_Moinhat_Result> USP_Get_Ngoaingu_Moinhat(string codetv, string loaingoaingu)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            var loaingoainguParameter = loaingoaingu != null ?
                new ObjectParameter("loaingoaingu", loaingoaingu) :
                new ObjectParameter("loaingoaingu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Ngoaingu_Moinhat_Result>("USP_Get_Ngoaingu_Moinhat", codetvParameter, loaingoainguParameter);
        }
    
        public virtual ObjectResult<USP_Get_Relationship_Info_Result> USP_Get_Relationship_Info(string crewID)
        {
            var crewIDParameter = crewID != null ?
                new ObjectParameter("CrewID", crewID) :
                new ObjectParameter("CrewID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Relationship_Info_Result>("USP_Get_Relationship_Info", crewIDParameter);
        }
    
        public virtual ObjectResult<USP_Get_Relative_Result> USP_Get_Relative(string codetv, Nullable<int> loai)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Relative_Result>("USP_Get_Relative", codetvParameter, loaiParameter);
        }
    
        public virtual ObjectResult<USP_Get_TOEIC_By_Create_Time_Result> USP_Get_TOEIC_By_Create_Time(Nullable<System.DateTime> tungay, Nullable<System.DateTime> toingay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var toingayParameter = toingay.HasValue ?
                new ObjectParameter("toingay", toingay) :
                new ObjectParameter("toingay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_TOEIC_By_Create_Time_Result>("USP_Get_TOEIC_By_Create_Time", tungayParameter, toingayParameter);
        }
    
        public virtual ObjectResult<USP_Get_Toeic_Moinhat_Result> USP_Get_Toeic_Moinhat(string codetv)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Toeic_Moinhat_Result>("USP_Get_Toeic_Moinhat", codetvParameter);
        }
    
        public virtual ObjectResult<USP_GetOtherLanguage_Result> USP_GetOtherLanguage(string codetv)
        {
            var codetvParameter = codetv != null ?
                new ObjectParameter("codetv", codetv) :
                new ObjectParameter("codetv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetOtherLanguage_Result>("USP_GetOtherLanguage", codetvParameter);
        }
    
        public virtual ObjectResult<USP_Get_Address_Result> USP_Get_Address(string crewID)
        {
            var crewIDParameter = crewID != null ?
                new ObjectParameter("CrewID", crewID) :
                new ObjectParameter("CrewID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Address_Result>("USP_Get_Address", crewIDParameter);
        }
    }
}
