//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Account
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public string Account { get; set; }
        public string FirstNameVn { get; set; }
        public string LastNameVn { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> PPort_Date { get; set; }
        public Nullable<System.DateTime> PPort_Expired { get; set; }
        public Nullable<int> InfoConfirmed { get; set; }
        public Nullable<bool> IsCrew { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpired { get; set; }
        public string Code_tv { get; set; }
        public string name_tv { get; set; }
        public string name { get; set; }
        public Nullable<bool> man { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string noisinh { get; set; }
        public string quoctich { get; set; }
        public string pag_no { get; set; }
        public string pport_no { get; set; }
        public string noicap { get; set; }
        public string Group { get; set; }
        public string course { get; set; }
        public string main_base { get; set; }
        public string from_place { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string home { get; set; }
        public string type_tv { get; set; }
        public string term_tv { get; set; }
        public string class_tv { get; set; }
        public Nullable<bool> ann { get; set; }
        public string lg { get; set; }
        public string on_plan { get; set; }
        public string on_route { get; set; }
        public string vip { get; set; }
        public string knbgoc { get; set; }
        public string kn_khac { get; set; }
        public string status { get; set; }
        public string baclg { get; set; }
        public Nullable<System.DateTime> ngaynhan { get; set; }
        public Nullable<System.DateTime> ngayve { get; set; }
        public Nullable<float> ttut { get; set; }
        public Nullable<float> ma_tt { get; set; }
        public Nullable<int> fly_time { get; set; }
        public Nullable<int> int_time { get; set; }
        public Nullable<int> duty_time { get; set; }
        public Nullable<int> sochbay { get; set; }
        public Nullable<int> dubi { get; set; }
        public Nullable<int> night { get; set; }
        public string lc { get; set; }
        public string Email { get; set; }
        public string ImageBase64 { get; set; }
        public string Note { get; set; }
        public string Ogranization { get; set; }
        public string A321 { get; set; }
        public string A330 { get; set; }
        public string A350 { get; set; }
        public string B787 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public string Employer { get; set; }
        public string EngName { get; set; }
        public Nullable<double> EngScore { get; set; }
        public Nullable<System.DateTime> EngValid { get; set; }
        public string Education { get; set; }
    }
}
