//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SalaryLCDDetail
    {
        public int c_PID { get; set; }
        public string c_CrewID { get; set; }
        public byte c_EmployerID { get; set; }
        public System.DateTime c_FrTime { get; set; }
        public System.DateTime c_ToTime { get; set; }
        public string c_Code { get; set; }
        public int c_CodeMappingPID { get; set; }
        public decimal c_Hours { get; set; }
        public decimal c_DayValueOfDuty { get; set; }
        public short c_Priority { get; set; }
        public string c_Note { get; set; }
        public string c_PeriodTag { get; set; }
        public string c_RunTag { get; set; }
        public string c_RunRemark { get; set; }
        public bool c_IsDeleted { get; set; }
    }
}
