//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SalaryLCBDetail
    {
        public long c_PID { get; set; }
        public string c_CrewID { get; set; }
        public string c_CrewName { get; set; }
        public byte c_EmployerID { get; set; }
        public string c_Base { get; set; }
        public string c_ContractType { get; set; }
        public int c_FlightID { get; set; }
        public string c_FlightNo { get; set; }
        public string c_FrAirport { get; set; }
        public string c_ToAirport { get; set; }
        public bool c_FrAirportDom { get; set; }
        public bool c_ToAirportDom { get; set; }
        public System.DateTime c_UTC_STD { get; set; }
        public System.DateTime c_UTC_ATD { get; set; }
        public byte c_TimeZone_D { get; set; }
        public System.DateTime c_UTC_STA { get; set; }
        public System.DateTime c_UTC_ATA { get; set; }
        public byte c_TimeZone_A { get; set; }
        public string c_AircarftType { get; set; }
        public string c_FlightCarry { get; set; }
        public decimal c_FlyingMinsS { get; set; }
        public decimal c_FlyingMinsA { get; set; }
        public string c_JobTitle { get; set; }
        public string c_JobDuty { get; set; }
        public string c_JobSalary { get; set; }
        public string c_JobCA { get; set; }
        public bool c_JobVIP { get; set; }
        public decimal c_UnitPrice { get; set; }
        public decimal c_UnitPriceFC { get; set; }
        public string c_UnitPriceRemark { get; set; }
        public decimal c_Total { get; set; }
        public decimal c_TotalFC { get; set; }
        public string c_SalaryGroup { get; set; }
        public bool c_HoTroBayKem { get; set; }
        public decimal c_PhuCapBayKem { get; set; }
        public decimal c_PhuCapPhatNgon { get; set; }
        public decimal c_PhuCapBayCharter { get; set; }
        public decimal c_PhuCapNgoaiBase { get; set; }
        public decimal c_LuongBayTet { get; set; }
        public bool c_IsForLTU { get; set; }
        public string c_Note { get; set; }
        public string c_PeriodTag { get; set; }
        public string c_RunTag { get; set; }
        public bool c_IsDeleted { get; set; }
        public System.DateTime c_CreatedAt { get; set; }
        public decimal c_FlyingMinsFT4H { get; set; }
        public System.DateTime c_DataOfMonth { get; set; }
    }
}
