//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_TrainingClass
    {
        public int c_PID { get; set; }
        public string c_Name { get; set; }
        public short c_TrainingTypeID { get; set; }
        public string c_Location { get; set; }
        public System.DateTime c_FrDate { get; set; }
        public System.DateTime c_ToDate { get; set; }
        public string c_TimeDefault { get; set; }
        public decimal c_FrHours { get; set; }
        public decimal c_ToHours { get; set; }
        public Nullable<System.DateTime> c_TestDate { get; set; }
        public byte c_NumOfDay { get; set; }
        public short c_NumOfStudent { get; set; }
        public byte c_NumOfDocs { get; set; }
        public short c_MaxStudents { get; set; }
        public string c_ExcludingDays { get; set; }
        public byte c_ClassNature { get; set; }
        public byte c_DaysInWeek { get; set; }
        public byte c_ConditionMax { get; set; }
        public string c_ConditionTitle { get; set; }
        public string c_FileCode { get; set; }
        public string c_Note { get; set; }
        public string c_DocQualified { get; set; }
        public byte c_WarningCount { get; set; }
        public byte c_LogCount { get; set; }
        public byte c_TeacherCount { get; set; }
        public System.DateTime c_UpdatedAt { get; set; }
        public string c_UpdatedBy { get; set; }
        public bool c_IsDeleted { get; set; }
        public short c_ResultCount { get; set; }
    }
}
