//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_TrainingTypeProgramCategory
    {
        public int c_PID { get; set; }
        public short c_TrainingTypeID { get; set; }
        public string c_Name { get; set; }
        public string c_Code { get; set; }
        public byte c_DayCount { get; set; }
        public string c_TeacherAbilities { get; set; }
        public byte c_TeacherCount { get; set; }
        public bool c_IsDeleted { get; set; }
        public bool c_IsDeactivated { get; set; }
        public string c_Note { get; set; }
        public System.DateTime c_UpdatedAt { get; set; }
        public string c_UpdatedBy { get; set; }
    }
}
