//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tamhoanhd
    {
        public int id { get; set; }
        public int id_ns { get; set; }
        public string hoanhd_soqd { get; set; }
        public System.DateTime hoanhd_ngayky { get; set; }
        public System.DateTime hoanhd_tungay { get; set; }
        public System.DateTime hoanhd_denngay { get; set; }
        public int hoanhd_lydo { get; set; }
        public string hoanhd_soqdcdhoan { get; set; }
        public Nullable<System.DateTime> hoanhd_ngaykycdhoan { get; set; }
        public Nullable<System.DateTime> hoanhd_ngaycdhoanhl { get; set; }
        public Nullable<int> hoanhd_lydochamdut { get; set; }
        public bool hoanhd_tinhtrang { get; set; }
    
        public virtual qlttlaodong qlttlaodong { get; set; }
    }
}
