//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbQuyetDinh
    {
        public int id { get; set; }
        public int hd_loai_quyet_dinh { get; set; }
        public string hd_so_quyet_dinh { get; set; }
        public System.DateTime hd_ngay_ky_quyet_dinh { get; set; }
        public int hd_cap_ky_quyet_dinh { get; set; }
        public string hd_nguoi_ky_quyet_dinh { get; set; }
        public System.DateTime hd_ngay_hieu_luc { get; set; }
        public Nullable<System.DateTime> hd_ngay_het_hieu_luc { get; set; }
        public int hd_ly_do_chinh { get; set; }
        public int hd_tinh_trang { get; set; }
        public string hd_tom_tat_phu_luc_trong_quyet_dinh { get; set; }
        public string FileAnhVanBan { get; set; }
        public string nhansulienquan { get; set; }
    }
}
