//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Crew_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_GSHH
    {
        public int ID { get; set; }
        public string CrewID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Info { get; set; }
        public Nullable<bool> Theory { get; set; }
        public Nullable<bool> B787 { get; set; }
        public Nullable<bool> A350 { get; set; }
        public Nullable<bool> A321 { get; set; }
        public string Note { get; set; }
        public string ModifierID { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> SCCS { get; set; }
    }
}
